CREATE TABLE `spotifyhits` (
	`SpotifyID` INT(10) NOT NULL AUTO_INCREMENT,
	`MSISDN` VARCHAR(50) NULL DEFAULT NULL,
	`PROCESS_DATE` DATE NULL DEFAULT NULL,
	`PROCESS_TIME` TIMESTAMP NULL DEFAULT NULL,
	`OPID` VARCHAR(50) NULL DEFAULT NULL,
	`METHODID` VARCHAR(50) NULL DEFAULT NULL,
	`RETURNMESSAGE` VARCHAR(50) NULL DEFAULT NULL,
	`RETURNCLIENTID` VARCHAR(256) NULL DEFAULT NULL,
	`ENTIRELINE` VARCHAR(2500) NULL DEFAULT NULL,
	`UPDATEDTIME` TIMESTAMP NULL DEFAULT NULL,
	`UPDATED_DATE` DATE NULL DEFAULT NULL,
	`RETURN_CODE` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`SpotifyID`)
)